<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Space\SalesCountdown\ViewModel\Catalog\Product\View\SalesCountdown
 * @var $escaper \Magento\Framework\Escaper
 */

$viewModel = $block->getData('view_model');
?>
<?php if (null !== $viewModel && !empty($viewModel->getSpecialToDate())): ?>
    <div id="sales-countdown" class="sales-countdown">
        <p><?= $escaper->escapeHtml($viewModel->getSpecialToDate()) ?></p>
    </div>
<?php endif; ?>
